spring.application.name=apiRadar

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/bd_apiusuarios
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.datasource.password=ass_coti

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
