spring.application.name=apiRadar

server.port=8080

#spring.datasource.url=jdbc:postgresql://localhost:5432/bd_apiusuarios
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.username=postgres
#spring.datasource.password=ass_coti

spring.datasource.url=jdbc:postgresql://localhost:5432/bdusuariosapi
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=ass
spring.datasource.password=ass


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.key.open.data.nasa=sIBefPigqDwqlDiafpNqLAvFcnfM0sT0aMv3dEpQ
api.key.weather=ed0309dc-efc0-11ef-85cb-0242ac130003-ed030a86-efc0-11ef-85cb-0242ac130003
